/twike/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
  
    tricycle_steering_controller:
      type: tricycle_steering_controller/TricycleSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/twike/joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false
    extra_joints: ["front_wheel_joint"]
    frame_id: base_footprint

/twike/tricycle_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    traction_joints_names: [rear_left_wheel_joint, rear_right_wheel_joint]
    steering_joints_names: [front_steering_wheel_joint]
    base_frame_id: base_footprint
    wheelbase: 0.4
    traction_wheels_radius: 0.1
    traction_track_width: 0.3